# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'OTT-Applcation' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for OTT-Applcation
  pod 'SocialLogin', :path=> '../../SocialLogin/SocialLogin'
#  pod 'SocialLogin/KeychainAccess', :path=> '../../SocialLogin/SocialLogin/'

end
